version: "3.5"
services: 
  webserver:
    image: nginx:alpine
    container_name: nginx_game
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    depends_on: 
      - player1
      - player2
    networks:
      - game
  player1:
    image: tic
    expose:
      - "8000"
    networks: 
      - game  
  player2:
    image: tic
    expose:
      - "8000"
    networks: 
      - game
networks:
  game:
    driver: bridge